version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:CDWpYliGtPf7m0ld84aJyHtwkNee2ivMTOQf7yr2x1A"
      - checkout
      - run: echo "A first hello1"
      - run: npm -v
      - run: node -v
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
